#!/usr/bin/env python3

"""
google

Google from the command line. Requires the ever-useful OS X 'open' command.
"""

import os
import sys

words = sys.argv[1:]
url = 'http://www.google.com/search?q=' + '+'.join(words)
command = 'open "{}"'.format(url)
os.popen(command)