#!/usr/bin/env bash

# webshot
# Automates taking screenshots at exactly the right size using webkit2png.
# Usage: webshot <file to take picture of> <desired filename>
webkit2png "$1" -W 1000 -H 800 -F -o "$2";
mv "$2-full.png" "$2";
convert -crop 2000x1600+0+0 "$2" "$2";
